name: zaza_app
description: "Zaza App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #State Management
  flutter_bloc: ^8.1.4

  #powerful HTTP networking
  dio: ^5.4.1

  #Secure Storage
  flutter_secure_storage: ^9.0.0

  #Shared Preferences
  shared_preferences: ^2.2.2

  #Date Format
  intl: any

  #Email Validator
  email_validator: ^2.1.17

  #Flutter Toast
  fluttertoast: ^8.2.4

  #Conditional Builder
  conditional_builder_null_safety: ^0.0.6

  #Permission Handler
  permission_handler: ^11.3.0

  #Screenutil
  flutter_screenutil: ^5.9.0

  #Cached Network Image
  cached_network_image: ^3.3.1

  #Comparing Dart Objects
  equatable: ^2.0.5

  #Service Locator
  get_it: ^7.6.7

  #Page Transition
  page_transition: ^2.1.0

  #Flutter Svg
  flutter_svg: ^2.0.10

  #Hive (Local Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Curved Navigation Bar
  curved_navigation_bar: ^1.0.3

  #Persistent Navigation Bar
  persistent_bottom_nav_bar: ^5.0.2

  #Barcode Scanner
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.4

  #Flutter Spinkit
  flutter_spinkit: ^5.2.0

  #Phone Number Input
  intl_phone_number_input: ^0.7.4

  #Awesome Dialog
  awesome_dialog: ^3.2.0

  #Contained_tab_bar_view
  contained_tab_bar_view: ^0.8.0

  #Like Button
  like_button: ^2.0.5

  #Go Router
  go_router: ^13.2.0

  #internet_connection_checker
  internet_connection_checker: ^1.0.0+1

  #device_info_plus
  device_info_plus: ^9.1.2

  #Shimmer
  shimmer: ^3.0.0

  #make request to api
  retrofit: ^4.1.0

  #Languages
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/Logo1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logos/Logo1024.png"
  image_path_ios: "assets/images/logos/Logo1024.png"


  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 1000 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true


flutter:

  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logos/
    - assets/images/onboarding/
    - assets/images/basket/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700